name: release

on:
  push:
    tags:
    - 'v*'

env:
  PLUGIN_NAME: obsidian-simple-day-planner

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: use node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - name: npm package-lock.json ssh/https hack
      run: git config --global url."https://github.com/".insteadOf ssh://git@github.com/
    - name: cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-
    - name: install dependencies
      run: npm clean-install --ignore-scripts
    - name: test
      run: npm test
    - name: build
      id: build
      run: | 
        npm run build --if-present
        mkdir ${{ env.PLUGIN_NAME }}
        cp dist/* ${{ env.PLUGIN_NAME }}
        zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
        ls
        echo "::set-output name=tag_name::$(git tag --sort version:refname | tail -n 1)"
    - name: release
      id: release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: ${{ github.ref }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: no
        prerelease: yes
    - name: upload
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }} 
        asset_path: ./${{ env.PLUGIN_NAME }}.zip 
        asset_name: ${{ env.PLUGIN_NAME }}-${{ steps.build.outputs.tag_name }}.zip 
        asset_content_type: application/zip
